name: ba3_bs_mobile
description: "BA3 Business Solutions App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.8.0+1
  pluto_grid: ^8.0.0
  fluttertoast: ^8.2.12
  intl: 0.19.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  dartz: ^0.10.1
  nfc_manager: ^3.5.0
  window_manager: ^0.4.3
  native_dialog_plus: ^1.0.9
  flutter_platform_alert: ^0.7.0
  syncfusion_flutter_datagrid: ^28.2.7
  syncfusion_flutter_datepicker: ^28.2.7
  flutter_material_color_picker: ^1.2.0
  tab_container: ^3.5.3
  math_expressions: ^2.7.0
  image: ^4.5.3
  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4
  http: ^1.3.0
  path_provider: ^2.1.5
  mailer: ^6.4.1
  qr_flutter: ^4.1.0
  pdf: ^3.11.3
  equatable: ^2.0.7
  flutter_keyboard_visibility: ^6.0.0
  shared_preferences: ^2.3.4
  geolocator: ^13.0.2
  simple_barcode_scanner: ^0.3.0
  #  flutter_barcode_scanner: ^2.0.0
  day_night_time_picker: ^1.3.1
  file_picker: ^9.0.1
  xml: ^6.5.0
  logger: ^2.5.0
  syncfusion_flutter_gauges: ^28.2.7
  animated_text_kit: ^4.2.3
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  dropdown_button2: ^2.3.9
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/notoSansArabic/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/notoSansArabic/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/notoSansArabic/NotoSansArabic-Bold.ttf
          weight: 700

    - family: Almarai
      fonts:
        - asset: assets/fonts/almarai/AlmaraiRegular.ttf