# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #
#
# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane
#
#
# default_platform(:android)
#
# platform :android do
#   desc "Distribute the app to Firebase App Distribution"
#   lane  :deploy_to_firebase do
#     sh "flutter build apk"
#     firebase_app_distribution(
#       app: ENV["FIREBASE_APP_ID"].strip,
#       groups: "testers",
#       release_notes: "This Fastlane Build",
#       firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"].strip,
#       android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
#       android_artifact_type: "APK",
#       debug: true
#     )
#   end
# end

default_platform(:android)

platform :android do
  desc "Distribute the app to Firebase App Distribution"
  lane  :deploy_to_firebase do
    sh "flutter build apk"
    firebase_app_distribution(
      app: "1:307353344258:android:7c0b16dc5261f883f78a1b",
      groups: "testers",
      release_notes: "This Fastlane Build",
      firebase_cli_token: "1//09LXYcrcj4BX2CgYIARAAGAkSNwF-L9IrRXiF-cBTEjSP3HY_rQbYleJ8Mjcs4BWCBEwpfzhkUpv3TvOIhY4fo5wMXOs4L1r10i0",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      android_artifact_type: "APK",
      debug: true
    )
  end
end